---
- name: installing and launching filebeat
  hosts: webservers
  become: yes
  tasks:
    
	# Download metricbeat package from elastic.co
	
  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.2-amd64.deb
    
	# Install downloaded metricbeat file
	
  - name: install metricbeat deb
    command: sudo dpkg -i metricbeat-7.6.2-amd64.deb
    
	# Implant config file from /ansible/files/ into /etc/metricbeat/
	
  - name: drop in metricbeat.yml
    copy:
      src : /etc/ansible/files/metricbeat.yml
      dest: /etc/metricbeat/metricbeat.yml
    
    # Enable metricbeat
	
  - name: enable and configure system module
    command: metricbeat modules enable system
    
	# Connect metricbeat to ELK server
	
  - name: setup metricbeat
    command: metricbeat setup
    
	# Start metricbeat service
	
  - name: start metricbeat service
    command: service metricbeat start
